
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkmmbhwirvniuayiidbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrbW1iaHdpcnZuaXVheWlpZGJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDIzNTgsImV4cCI6MjA2MzMxODM1OH0.FafJEtaheLHrUIX1M3phrlSmVVPAYMRciZraIftYa7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
